2018:
 - Awardee: "Zena Ariola"
   Citation: |
     Zena Ariola has been the founder and long-time organizer (together with a
     rotating board) of the Oregon Programming Languages Summer School
     (OPLSS). The school has run annually for over 15 years and has been
     immensely successful. It is now the de facto forum for establishing a
     common baseline in educating PL Ph.D. students (and often M.Sc.  and
     advanced undergraduates), especially in the US, but also, to an increasing
     extent, internationally. The school is a large part of what has made PL a
     community with shared principles in the past two decades, especially for
     young scientists. The quality of the event has been extremely high.

     Annual participation has risen to over 100 students. In total, OPLSS has
     attracted over 1100 students and 160 speakers; over 750 hours of content
     has been delivered, with lecture notes and videos available through the
     OPLSS archives and on YouTube. Since its inception, OPLSS has received
     annual support from SIGPLAN and the National Science Foundation. The school
     has also been consistently successful at attracting substantial industrial
     support, from companies such as BAE, Draper Laboratories, Facebook, Google,
     and Microsoft. This funding is used to pay the operating costs of the
     program, but, more importantly, subsidizes the participation of students
     from smaller departments and foreign students. The school affords great
     networking opportunities and a thorough treatment of topics, especially in
     theoretical PL. Former students speak glowingly of the warm and supportive
     atmosphere, the emphasis on inclusion for less-experienced students, the
     networking and mentoring among women in computer science, and the chance to
     meet leading researchers and be exposed to their work. Quite often students
     speak of the school as having changed the direction of their lives, for
     example choosing to study programming languages in graduate school. An
     important component of the school's success has been its fixed location at
     the University of Oregon.

     By establishing and running OPLSS, Prof Ariola has made an enormous
     contribution to the field of programming languages.

2017:
 - Awardee: "&nbsp;"
   Citation: |
     No award made.

2016:
- Awardee: "Phil Wadler"
  Citation: |
    Phil Wadler has been a tireless promoter of Programming Languages
    for over two decades.  He has served in numerous heavy-service
    roles, including PC Chair of large conferences (such as ICFP and
    POPL), founding editor and editor-in-chief of the Journal of
    Functional Programming, member and later Chair of the SIGPLAN
    executive committee, PL area editor for the Journal of the ACM,
    and many more.  In his ceaseless efforts to popularize deep
    concepts, Phil has given talks at several developer conferences,
    mentoring workshops, and summer schools; has never shied away from
    less glamorous service assignments (such as editing the Functional
    Programming column of SIGPLAN Notices or moderating the Types
    electronic forum); and has written two introductory books, on
    Functional Programming and on Java Generics.  Phil is also
    responsible for the introduction of Functional Pearls as a paper
    class, since then regularly adopted by ICFP and POPL.

2015:
- Awardee: "Dan Grossman"
  Citation: |
    Dan Grossman has made significant contributions to programming
    languages education.  Roughly once a decade, the ACM and IEEE
    Computer Society publish revised curriculum recommendations for
    undergraduate-level computer science education.  The 2001
    Curriculum Recommendations included very little PL content, mostly
    material suitable for a CS1 course.  As a member of the 2013
    ACM/IEEE-CS Computing Curriculum Steering Committee, Dan was
    largely responsible for the revisions to the PL curriculum that
    reintroduced substantial up-to-date PL topics into the curriculum.
    This effort included convincing the steering committee and
    soliciting input from many members of the PL community. As part of
    these efforts, Dan also served as the chair of the SIGPLAN
    Education Board during his term as Member-at-Large on the SIGPLAN
    Executive Committee.  Serving currently on the ACM Education
    Board, he continues to be an effective advocate for excellence in
    programming languages education.

2014:
- Awardee: "Simon Peyton Jones"
  Citation: |
    Simon Peyton Jones has served the programming languages community
    for many years and in many capacities.  In addition to serving on
    the SIGPLAN Executive Committee and on numerous program committees
    for the major SIGPLAN conferences, he has served as both program
    and general chair for ICFP and program chair for POPL, and as
    editor-in-chief of the Journal of Functional Programming,
    published by Cambridge University Press.  His development and
    maintenance of GHC, the Glasgow Haskell Compiler, as well as his
    stewardship of the Haskell 98 standardization effort, have made
    Haskell into both an active research testbed and an
    industrial-strength language for commercial use, as recognized by
    the 2011 SIGPLAN Software Award.  Last but not least, he has
    played a major leadership role in the recent reform of computing
    education in the UK.  He co-founded and serves as chair of
    Computing at School, the group that was primarily responsible for
    the recent reform of the national curriculum; he was a member of
    the Royal Society working group that wrote the influential report
    "Shut down or restart: the way forward for computing in schools";
    and he chaired the group that drafted the new national programme
    of study for Computing.  Simon's investments in UK education are
    inspiring, and will pay dividends for generations to come.

2013:
- Awardee: "Kathleen Fisher"
  Citation: |
    Kathleen Fisher served on the SIGPLAN Executive committee for
    twelve years, from 2001 to 2012, taking on in succession the roles
    of member-at-large, vice-chair, chair, and past chair.  During
    that time she worked tirelessly to promote programming languages
    among researchers and students.  She has served as program chair
    for many major conferences, including ICFP 2004, CUFP 2006,
    FOOL/WOOD 2006-7, OOPSLA and SPLASH 2011.  Kathleen has also
    served on the board of the CRA, co-chaired CRA's Committee on the
    Status of Women, and edited the Journal of Functional Programming.
    She chairs the PLDI steering committee, and will be general chair
    for ICFP 2015.

    When Kathleen sees a problem, she takes action to fix it.  For
    example, seeing that programming languages were being neglected in
    Computer Science curriculum recommendations, she spearheaded an
    influential workshop and community effort that led to an increased
    role for programming languages in the ACM Curriculum, including
    new emphasis on polymorphism, higher-order functions, type
    systems, static analysis, and garbage collection.  Concerned that
    students were not entering programming languages research, she, in
    collaboration with Ron Garcia and Stephanie Weirich, organized and
    secured funding for the first Programming Languages Mentoring
    Workshop, held at POPL in Philadelphia in 2012, and is helping to
    ensure the continuation of this event by serving on its steering
    committee.

    Kathleen's enthusiasm for programming languages, and for life,
    prompted many of today's volunteers to take the first steps toward
    involvement in SIGPLAN affairs.  The Executive Committee misses
    her wit, wisdom and guidance, but feels that she has truly earned
    the 2013 Distinguished Service Award.

2012:
- Awardee: "Jens Palsberg"
  Citation: |
    The 2012 SIGPLAN service award goes to Jens Palsberg, who has led
    or served on an extraordinary number of program committees, mostly
    for SIGPLAN conferences and workshops.  He was program chair of
    X10 '12, POPL '10, co-chair of SAS '09, chair of PDM '09, chair of
    EMSOFT in '08, chair of TACAS '06, chair of MemoCode '06, chair
    SREIS '02, co-chair of PASTE '02, and chair of SAS '00.  He is
    general co-chair for ICESS '12, and previously was general chair
    of ICESS'10, SPIN in '08, POPL in '05, and conference chair for
    LICS in '09. He has been on the committees for almost 100
    conferences and workshops between 1994 and 2013&#8212;an average
    of more than 5 per year over a 19 year period.  Major conferences
    include POPL (3), PLDI (3), OOPSLA (3), ECOOP (11), SAS (7), ICSE
    (2), and EMSOFT(4).

    Jens is the Editor-in-Chief for TOPLAS, having previously served
    as an associate editor.  He is also on the SIGPLAN CACM Research
    Highlights Selection Committee, and on the Information &
    Computation Editorial Board. He was previously secretary/treasurer
    of SIGBED, and while his work in the SIGBED community is not
    directly related to SIGPLAN, he has actively contributed a
    languages-oriented perspective and agenda to that community.

    The high quality of conferences and journals in our field depends
    on diligent service on program committees and by editors.  This
    award is a small way of thanking Jens for the decades of service
    he has given to our community in these vital roles.

2011:
- Awardee: "Kathryn S. McKinley"
  Citation: |
    Kathryn has served the SIGPLAN community for many years as a
    researcher, educator, mentor, reviewer, and leader. She has worked
    in a number of formal SIGPLAN leadership roles, including
    co-Editor of TOPLAS, Associate Editor of TACO, Program Chair for
    ASPLOS and PLDI, Editor of "20 Years of PLDI (1979-1999)", and as
    a leading proponent of the double-blind reviewing procedures now
    adopted by many SIGPLAN conferences. She has served on the PLDI,
    ASPLOS, and OOPSLA steering committees, and as Secretary and
    Treasurer of the SIGPLAN Executive Committee.

    Kathryn's service to the broader programming-language community
    beyond SIGPLAN extends to her activities on the CRA-W Board,
    organizer of the CRA-W Programming Language Summer School and
    CRA-W Workshop on Programming Languages, Operating Systems, and
    Architecture. Kathryn has served on the program committees of
    SIGPLAN's ASPLOS, PLDI, OOPSLA, CGO, MSP, and ISMM conferences,
    and on other ACM and IEEE conferences such as PACT (for which she
    also served as program chair), SIGMETRICS, CC, ICPP, and ISCA.

    As a measure of her mentoring skills, Kathryn's students have
    distinguished themselves by winning prestigious awards such as
    SIGPLAN's Outstanding Doctoral Dissertation Award, PLDI's Student
    Research Competition, and several Best Presentation awards at
    SIGPLAN conferences. They have won prestigious graduate Research
    Fellowships from Microsoft, Intel, Samsung, and the National
    Science Foundation. As a member of the SIGPLAN community and
    representative to the broader computing community, Kathryn has
    hugely influenced the choices of many to pursue successful careers
    in programming language research and development.

2010:
- Awardee: "Jack W. Davidson"
  Citation: |
    Jack Davidson has contributed to the SIGPLAN community for many
    years, including as SIGPLAN chair (2005-2007), the SIGPLAN
    Communication Director (1999-present), a member of the SIGPLAN
    CACM Research Highlights Nominating Committee, a member of the ACM
    Publications Board, a member of the ACM SIG Governing Board and as
    its representative to the ACM Council, Associate Editor of ACM
    Transactions on Programming Languages and Systems, Associate
    Editor of ACM Transactions on Computer Architecture and
    Optimization, General Chair of PLDI (1998), chair of the PLDI
    steering committee (2009-2012), co-chair of LCTES (2000), chair of
    the LCTES steering committee (2001-2003), and a member of many
    conference program committees. Jack was instrumental in the
    development of LCTES as a SIGPLAN conference. As the Chair of
    SIGPLAN, Jack orchestrated the establishment of several SIGPLAN
    awards, including the Most Influential Paper Awards for OOPSLA and
    ICFP and the John Vlissides Award. In sum, Jack has made
    substantial and sustained contributions to the programming
    languages research community and to SIGPLAN in particular.

2009:
- Awardee: "Mamdouh Ibrahim"
  Citation: |
    For the past 15 years, Mamdouh Ibrahim has served the SIGPLAN
    community by helping to organize, to run, and to envision the
    future of OOPSLA, SIGPLAN's largest conference. Dr. Ibrahim served
    as Workshop Chair in 1993, Demonstration Chair in 1994, Poster
    Chair in 1995, Experience Report Chair in 1996, Tutorial Chair in
    1997, Publicity Chair in 1999, Treasurer in 2000 and 2001, and
    Conference Chair in 2002. He served on the program committee in
    1996 and 1997. He served on the Steering Committee from 2003 to
    2008, chairing the committee from 2005 to 2008. During this
    period, OOPSLA faced significant challenges because of drops in
    attendance caused by terrorist attacks, economic downturns, and
    shifting technological trends. Throughout his tenure, Dr. Ibrahim
    has served with good humor, skillful organization, and dedication,
    finding creative solutions to a variety of challenges and
    recruiting other dedicated people to join the organization.

2008:
- Awardee: "Michael G. Burke"
  Citation: |
    For many years, Michael Burke has served the SIGPLAN community
    with distinction through his professional activities as well as
    through his widely known and respected research. His SIGPLAN
    service has spanned a number of roles, including SIGPLAN
    Member-at-Large from 1997 to 2001, Vice Chair from 2001 to 2003,
    SIGPLAN Chair from 2003 to 2005, and Past Chair from 2005 to
    2007. During his time on the SIGPLAN Executive Committee, Mike
    spearheaded the effort to introduce Most Influential Paper Awards
    for POPL and PLDI, awards that were eventually also adopted by
    OOPSLA and ICFP. Mike has also given his valuable time in a number
    of capacities to the PLDI community: as a program committee member
    in 1990 and 1995, Program Chair in 1996, General Chair in 2001,
    and Chair of the Steering Committee from 2007 to 2009. He is
    currently serving as an Associate Editor of ACM's Transactions on
    Programming Languages and Systems (TOPLAS), which is widely viewed
    by SIGPLAN members as the premier forum for publishing their
    research.

2007:
- Awardee: "Linda Northrop"

2006:
- Awardee: "Hans Boehm"

2005:
- Awardee: "No award given"

2004:
- Awardee: "Ron Cytron"

2003:
- Awardee: "Mary Lou Soffa"

2002:
- Awardee: "Andrew Appel"

2001:
- Awardee: "Barbara Ryder"

2000:
- Awardee: "David Wise"

1999:
- Awardee: "Loren Meissner"

1998:
- Awardee: "Brent Hailpern"

1997:
- Awardee: "Jan Lee"
- Awardee: "Jean Sammet"

1996:
- Awardee: "Dick Wexelblat"
- Awardee: "John Richards"
